package com.caravan.caravan;

import android.util.Log;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBQueryExpression;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.ComparisonOperator;
import com.google.gson.Gson;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.locks.Condition;

@DynamoDBTable(tableName = "caravan-mobilehub-2012693532-Cities")

public class CitiesDO extends DynamoCRUD {
    private String _cityId;
    private String _cityName;

    public CitiesDO(String key, String range) {
        this.setCityId(key);
        this.setCityName(range);
    }

    public CitiesDO() {}

    private DynamoDBMapper dynamoDBMapper;

    @DynamoDBHashKey(attributeName = "cityId")
    @DynamoDBAttribute(attributeName = "cityId")
    public String getCityId() {
        return _cityId;
    }

    public void setCityId(final String _cityId) {
        this._cityId = _cityId;
    }
    @DynamoDBRangeKey(attributeName = "cityName")
    @DynamoDBAttribute(attributeName = "cityName")
    public String getCityName() {
        return _cityName;
    }

    public void setCityName(final String _cityName) {
        this._cityName = _cityName;
    }

    public void read(String id, String name) {
        new Thread(new Runnable() {
            @Override
            public void run() {

                com.caravan.caravan.CitiesDO cityItem = dynamoDBMapper.load(
                        com.caravan.caravan.CitiesDO.class,
                        id,       // Partition key (hash key)
                        name);    // Sort key (range key)

                // Item read
                Log.d("City Item:", cityItem.toString());
            }
        }).start();
    }
}
